interface FirebaseErrors {
  [key: string]: string;
}

export const firebaseErrors: FirebaseErrors = {
  'Firebase: Error (auth/email-already-in-use).':
    'Email is already in use. Try another email',
};

export const BadUrls = [
  'www.pornhub.com',
  'www.youporn.com',
  'www.xhamster.com',
  'www.bellesa.com',
  'xvideos.com',
  'www.xnxx.com',
  'www.adultchat.net',
  'www.flingster.com',
  'www.chat-avenue.com',
  'www.chatville.com',
  'www.chatropolis.com',
  'www.321sexchat.com',
  'www.tinder.com',
  'www.match.com',
  'www.pof.com',
  'www.datehookup.dating',
  'www.okcupid.com',
  'www.eharmony.com',
];

export const collegeDomains = [
  { name: 'Abilene Christian University', domain: 'acu.edu' },
  { name: 'Adelphi University', domain: 'adelphi.edu' },
  { name: 'Agnes Scott College', domain: 'scottlan.edu' },
  { name: 'Air Force Institute of Technology', domain: 'afit.af.mil' },
  { name: 'Alabama A&M University', domain: 'aamu.edu' },
  { name: 'Alabama State University', domain: 'alasu.edu' },
  { name: 'Albertson College of Idaho', domain: 'acofi.edu' },
  { name: 'Albion College', domain: 'albion.edu' },
  { name: 'Alfred University', domain: 'alfred.edu' },
  { name: 'Allegheny College', domain: 'alleg.edu' },
  {
    name: 'Allentown College of Saint Francis de Sales',
    domain: 'allencol.edu',
  },
  { name: 'Alma College', domain: 'alma.edu' },
  { name: 'Alverno College', domain: 'alverno.edu' },
  { name: 'Ambassador University', domain: 'ambassador.edu' },
  { name: 'American Coastline University', domain: 'amercoastuniv.edu' },
  {
    name: 'American Graduate School of International Management',
    domain: 't-bird.edu',
  },
  { name: 'American International College', domain: 'aic.edu' },
  { name: 'American University', domain: 'american.edu' },
  { name: 'Amherst College', domain: 'amherst.edu' },
  { name: 'Andrews University', domain: 'andrews.edu' },
  { name: 'Angelo State University', domain: 'angelo.edu' },
  { name: 'Antioch College', domain: 'college.antioch.edu' },
  { name: 'Antioch New England', domain: 'antiochne.edu' },
  { name: 'Antioch University-Los Angeles', domain: 'antiochla.edu' },
  { name: 'Antioch University-Seattle', domain: 'seattleantioch.edu' },
  { name: 'Appalachian State University', domain: 'appstate.edu' },
  { name: 'Aquinas College', domain: 'aquinas.edu' },
  { name: 'Arizona State University', domain: 'asu.edu' },
  { name: 'Arizona State University West', domain: 'west.asu.edu' },
  { name: 'Arizona Western College', domain: 'awc.cc.az.us' },
  { name: 'Arkansas State University, Jonesboro', domain: 'astate.edu' },
  { name: 'Arkansas Tech University', domain: 'atu.edu' },
  { name: 'Armstrong State College', domain: 'armstrong.edu' },
  { name: 'Ashland University', domain: 'ashland.edu' },
  { name: 'Assumption College', domain: 'assumption.edu' },
  { name: 'Auburn University', domain: 'auburn.edu' },
  { name: 'Auburn University - Montgomery', domain: 'aum.edu' },
  { name: 'Augsburg College', domain: 'augsburg.edu' },
  { name: 'Augustana College (IL)', domain: 'augustana.edu' },
  { name: 'Augustana College (SD)', domain: 'augie.edu' },
  { name: 'Aurora University', domain: 'aurora.edu' },
  { name: 'Austin College', domain: 'austinc.edu' },
  { name: 'Austin Peay State University', domain: 'apsu.edu' },
  { name: 'Averett College', domain: 'averett.edu' },
  { name: 'Avila College', domain: 'avila.edu' },
  { name: 'Azusa Pacific University', domain: 'apu.edu' },
  { name: 'Babson College', domain: 'babson.edu' },
  { name: 'Baldwin-Wallace College', domain: 'baldwinw.edu' },
  { name: 'Ball State University', domain: 'bsu.edu' },
  { name: 'Baker University', domain: 'bakeru.edu' },
  { name: 'Baptist Bible College', domain: 'bbc.edu' },
  { name: 'Bard College', domain: 'bard.edu' },
  { name: 'Barry University', domain: 'barry.edu' },
  { name: 'Bastyr University', domain: 'bastyr.edu' },
  { name: 'Bates College', domain: 'bates.edu' },
  { name: 'Baylor College of Medicine', domain: 'bcm.tmc.edu' },
  { name: 'Baylor University', domain: 'baylor.edu' },
  { name: 'Beaver College', domain: 'beaver.edu' },
  { name: 'Belmont University', domain: 'belmont.edu' },
  { name: 'Beloit College', domain: 'beloit.edu' },
  { name: 'Bemidji State University', domain: 'bemidji.msus.edu' },
  { name: 'Benedictine College', domain: 'benedictine.edu' },
  { name: 'Bennington College', domain: 'bennington.edu' },
  { name: 'Bentley College', domain: 'bentley.edu' },
  { name: 'Berea College', domain: 'berea.edu' },
  { name: 'Berklee College of Music', domain: 'berklee.edu' },
  { name: 'Bethany College (CA)', domain: 'bethany.edu' },
  { name: 'Bethany College (WV)', domain: 'bethany.wvnet.edu' },
  { name: 'Bethel College (KS)', domain: 'bethelks.edu' },
  { name: 'Bethel College and Seminary (MN)', domain: 'bethel.edu' },
  { name: 'Biola University', domain: 'biola.edu' },
  { name: 'Birmingham-Southern College', domain: 'bsc.edu' },
  { name: 'Black Hills State University', domain: 'bhsu.edu' },
  { name: 'Bloomsburg University of Pennsylvania', domain: 'bloomu.edu' },
  { name: 'Bluffton College', domain: 'bluffton.edu' },
  { name: 'Bob Jones University', domain: 'bju.edu' },
  { name: 'Boise State University', domain: 'idbsu.edu' },
  { name: 'Boston College', domain: 'bc.edu' },
  { name: 'Boston Graduate School of Psychoanalysis', domain: 'bgsp.edu' },
  { name: 'Boston University', domain: 'bu.edu' },
  { name: 'Bowdoin College', domain: 'bowdoin.edu' },
  { name: 'Bowie State University', domain: 'bsu.umd.edu' },
  { name: 'Bowling Green State University', domain: 'bgsu.edu' },
  { name: 'Bradley University', domain: 'bradley.edu' },
  { name: 'Brandeis University', domain: 'brandeis.edu' },
  { name: 'Brenau University', domain: 'brenau.edu' },
  { name: 'Briar Cliff College', domain: 'briar-cliff.edu' },
  { name: 'Bridgewater College', domain: 'bridgewater.edu' },
  { name: 'Brigham Young University', domain: 'byu.edu' },
  { name: 'Brigham Young University Hawaii', domain: 'byuh.edu' },
  { name: 'Brown University', domain: 'brown.edu' },
  { name: 'Bryant College', domain: 'bryant.edu' },
  { name: 'Bryn Mawr College', domain: 'brynmawr.edu' },
  { name: 'Bucknell University', domain: 'bucknell.edu' },
  { name: 'Buena Vista University', domain: 'bvu.edu' },
  { name: 'Butler University', domain: 'butler.edu' },
  { name: 'California Coast University', domain: 'calcoastuniv.edu' },
  { name: 'California Institute of Technology', domain: 'caltech.edu' },
  { name: 'California Lutheran University', domain: 'callutheran.edu' },
  { name: 'California Maritime Academy', domain: 'csum.edu' },
  { name: 'California National University', domain: 'cnuas.edu' },
  {
    name: 'California Polytechnic State University, San Luis Obispo',
    domain: 'calpoly.edu',
  },
  {
    name: 'California State Polytechnic University, Pomona',
    domain: 'csupomona.edu',
  },
  { name: 'California State University System', domain: 'calstate.edu' },
  { name: 'California State University, Bakersfield', domain: 'csubak.edu' },
  { name: 'California State University, Chico', domain: 'csuchico.edu' },
  { name: 'California State University, Dominguez Hills', domain: 'csudh.edu' },
  { name: 'California State University, Fresno', domain: 'csufresno.edu' },
  { name: 'California State University, Fullerton', domain: 'fullerton.edu' },
  { name: 'California State University, Hayward', domain: 'csuhayward.edu' },
  { name: 'California State University, Long Beach', domain: 'csulb.edu' },
  {
    name: 'California State University, Los Angeles',
    domain: 'calstatela.edu',
  },
  { name: 'California State University, Monterey Bay', domain: 'monterey.edu' },
  { name: 'California State University, Northridge', domain: 'csun.edu' },
  { name: 'California State University, Sacramento', domain: 'csus.edu' },
  { name: 'California State University, San Bernardino', domain: 'csusb.edu' },
  { name: 'California State University, San Jose', domain: 'sjsu.edu' },
  { name: 'California State University, San Marcos', domain: 'csusm.edu' },
  { name: 'California State University, Stanislaus', domain: 'csustan.edu' },
  { name: 'California University of Pennsylvania', domain: 'cup.edu' },
  { name: 'Calvin College', domain: 'calvin.edu' },
  { name: 'Campbell University', domain: 'campbell.edu' },
  { name: 'Campbellsville College', domain: 'campbellsvil.edu' },
  { name: 'Cameron University', domain: 'cameron.edu' },
  { name: 'Canisius College', domain: 'canisius.edu' },
  { name: 'Carleton College', domain: 'carleton.edu' },
  { name: 'Carlow College', domain: 'carlow.edu' },
  { name: 'Carnegie Mellon University', domain: 'cmu.edu' },
  { name: 'Carroll College (MT)', domain: 'carroll.edu' },
  { name: 'Carroll College (WI)', domain: 'cc.edu' },
  { name: 'Carson-Newman College', domain: 'cn.edu' },
  { name: 'Carthage College', domain: 'carthage.edu' },
  { name: 'Case Western Reserve University', domain: 'cwru.edu' },
  { name: 'Castleton State University', domain: 'csc.vsc.edu' },
  { name: 'The Catholic University of America', domain: 'cua.edu' },
  { name: 'Cedarville College', domain: 'cedarville.edu' },
  { name: 'Centenary College of Louisiana', domain: 'centenary.edu' },
  { name: 'Central College', domain: 'central.edu' },
  { name: 'Central Connecticut State University', domain: 'ccsu.ctstateu.edu' },
  { name: 'Central Methodist College', domain: 'cmc.edu' },
  { name: 'Central Michigan University', domain: 'cmich.edu' },
  { name: 'Central Missouri State University', domain: 'cmsu.edu' },
  { name: 'Central Washington University', domain: 'cwu.edu' },
  { name: 'Centre College', domain: 'centre.edu' },
  { name: 'Chadron State College', domain: 'csc.edu' },
  { name: 'Champlain College', domain: 'champlain.edu' },
  { name: 'Chapman University', domain: 'chapman.edu' },
  { name: 'Chatham College', domain: 'chatham.edu' },
  { name: 'Chesapeake College', domain: 'chesapeake.edu' },
  { name: 'Cheyney University', domain: 'cheyney.edu' },
  {
    name: 'The Chicago School of Professional Psychology',
    domain: 'csopp.edu',
  },
  { name: 'Christian Brothers University', domain: 'cbu.edu' },
  { name: 'Christian Theological Seminary', domain: 'cts.edu' },
  { name: 'Christopher Newport University', domain: 'cnu.edu' },
  { name: 'The Citadel', domain: 'citadel.edu' },
  { name: 'City University', domain: 'cityu.edu' },
  { name: 'City University of New York', domain: 'cuny.edu' },
  { name: 'Claremont Graduate School', domain: 'cgs.edu' },
  { name: 'Claremont McKenna College', domain: 'mckenna.edu' },
  { name: 'Clarion University of Pennsylvania', domain: 'clarion.edu' },
  { name: 'Clark University', domain: 'clarku.edu' },
  { name: 'Clarke College', domain: 'clarke.edu' },
  { name: 'Clarkson University', domain: 'clarkson.edu' },
  { name: 'Clayton State College', domain: 'csc.peachnet.edu' },
  { name: 'Clemson University', domain: 'clemson.edu' },
  { name: 'Cleveland State University', domain: 'csuohio.edu' },
  { name: 'Clinch Valley College', domain: 'clinch.edu' },
  { name: 'Coastal Carolina University', domain: 'coastal.edu' },
  { name: 'Coe College', domain: 'coe.edu' },
  { name: 'Coker College', domain: 'coker.edu' },
  { name: 'Colby College', domain: 'colby.edu' },
  { name: 'Colgate University', domain: 'colgate.edu' },
  { name: 'College of the Atlantic', domain: 'coa.edu' },
  { name: 'College of Charleston', domain: 'cofc.edu' },
  { name: 'College of Eastern Utah', domain: 'ceu.edu' },
  { name: 'College of the Holy Cross', domain: 'holycross.edu' },
  { name: 'College of Saint Benedict', domain: 'csbsju.edu' },
  { name: 'College of Saint Catherine', domain: 'stkate.edu' },
  { name: 'College of St. Francis', domain: 'stfrancis.edu' },
  { name: 'College of Saint Rose', domain: 'strose.edu' },
  { name: 'College of St. Scholastica', domain: 'css.edu' },
  { name: 'College of William and Mary', domain: 'wm.edu' },
  { name: 'The College of Wooster', domain: 'wooster.edu' },
  { name: 'Colorado Christian University', domain: 'ccu.edu' },
  { name: 'Colorado College', domain: 'cc.colorado.edu' },
  { name: 'Colorado School of Mines', domain: 'mines.colorado.edu' },
  { name: 'Colorado State University', domain: 'colostate.edu' },
  { name: 'Columbia College Chicago', domain: 'colum.edu' },
  { name: 'Columbia Southern University', domain: 'colsouth.edu' },
  { name: 'Columbia Union College', domain: 'cuc.edu' },
  { name: 'Columbia University', domain: 'columbia.edu' },
  { name: 'Concordia College-Ann Arbor', domain: 'ccaa.edu' },
  { name: 'Concordia College-Moorhead', domain: 'cord.edu' },
  { name: 'Concordia College-St. Paul', domain: 'csp.edu' },
  { name: 'Concordia College-Seward', domain: 'ccsn.edu' },
  { name: 'Concordia University River Forest, Illinois', domain: 'cuis.edu' },
  { name: 'Connecticut College', domain: 'conncoll.edu' },
  {
    name: 'The Cooper Union for the Advancement of Science and Art',
    domain: 'cooper.edu',
  },
  { name: 'Coppin State College', domain: 'coppin.umd.edu' },
  { name: 'Cornell College', domain: 'cornell-iowa.edu' },
  { name: 'Cornell University', domain: 'cornell.edu' },
  { name: 'Creighton University', domain: 'creighton.edu' },
  { name: 'Curry College', domain: 'curry.edu' },
  { name: 'Daemen College', domain: 'daemen.edu' },
  { name: 'Dakota State University', domain: 'dsu.edu' },
  { name: 'Dakota Wesleyan University', domain: 'dwu.edu' },
  { name: 'Dallas Baptist University', domain: 'dbu.edu' },
  { name: 'Dana College', domain: 'dana.edu' },
  { name: 'Daniel Webster College', domain: 'dwc.edu' },
  { name: 'Dartmouth College', domain: 'dartmouth.edu' },
  {
    name: 'Davenport College Detroit College of Business',
    domain: 'davenport.edu',
  },
  { name: 'Davidson College', domain: 'davidson.edu' },
  { name: 'Davis & Elkins College', domain: 'dne.wvnet.edu' },
  { name: 'Delaware State University', domain: 'dsc.edu' },
  { name: 'Delta State University', domain: 'deltast.edu' },
  { name: 'Denison University', domain: 'denison.edu' },
  { name: 'DePaul University', domain: 'depaul.edu' },
  { name: 'DePauw University', domain: 'depauw.edu' },
  { name: 'DeVry Institute of Technology', domain: 'devrycols.edu' },
  { name: 'DeVry Institute of Technology-Dallas', domain: 'devry.edu' },
  { name: 'DeVry Institute of Technology-Phoenix', domain: 'devry-phx.edu' },
  { name: 'Dickinson College', domain: 'dickinson.edu' },
  { name: 'Dickinson State University', domain: 'dsu.nodak.edu' },
  { name: 'Dillard University', domain: 'dillard.edu' },
  { name: 'Dominican College', domain: 'dominican.edu' },
  { name: 'Dordt College', domain: 'Dordt.edu' },
  { name: 'Dowling College', domain: 'dowling.edu' },
  { name: 'Drake University', domain: 'drake.edu' },
  { name: 'Drew University', domain: 'drew.edu' },
  { name: 'Drexel University', domain: 'drexel.edu' },
  { name: 'Drury College', domain: 'drury.edu' },
  { name: 'Duke University', domain: 'duke.edu' },
  { name: 'Duquesne University', domain: 'duq.edu' },
  { name: 'Earlham College', domain: 'earlham.edu' },
  { name: 'East Carolina University', domain: 'ecu.edu' },
  { name: 'East Central University', domain: 'ecok.edu' },
  {
    name: 'East Stroudsburg State University of Pennsylvania',
    domain: 'esu.edu',
  },
  { name: 'East Tennessee State University', domain: 'etsu-tn.edu' },
  { name: 'East Texas State University', domain: 'etsu.edu' },
  { name: 'Eastern Connecticut State University', domain: 'ecsu.ctstateu.edu' },
  { name: 'Eastern Illinois University', domain: 'eiu.edu' },
  { name: 'Eastern Kentucky University', domain: 'eku.edu' },
  { name: 'Eastern Mennonite University', domain: 'emu.edu' },
  { name: 'Eastern Michigan University', domain: 'emich.edu' },
  { name: 'Eastern New Mexico University', domain: 'enmu.edu' },
  { name: 'Eastern Oregon State College', domain: 'eosc.osshe.edu' },
  { name: 'Eastern Washington University', domain: 'ewu.edu' },
  { name: 'Edgewood College', domain: 'edgewood.edu' },
  { name: 'Edinboro University of Pennsylvania', domain: 'edinboro.edu' },
  { name: 'Elizabeth City State University', domain: 'ecsu.edu' },
  { name: 'Elizabethtown College', domain: 'etown.edu' },
  { name: 'Elmhurst College', domain: 'elmhurst.edu' },
  { name: 'Elon College', domain: 'elon.edu' },
  { name: 'Embry-Riddle Aeronautical University, Arizona', domain: 'erau.edu' },
  { name: 'Embry-Riddle Aeronautical University, Florida', domain: 'erau.edu' },
  { name: 'Emerson College', domain: 'emerson.edu' },
  { name: 'Emmanuel College', domain: 'emmanuel.edu' },
  { name: 'Emporia State University', domain: 'emporia.edu' },
  { name: 'Emory University', domain: 'emory.edu' },
  { name: 'Evergreen State College', domain: 'evergreen.edu' },
  { name: 'Fairleigh Dickinson University', domain: 'fdu.edu' },
  { name: 'Fairmont State College', domain: 'fairmont.wvnet.edu' },
  { name: 'Fayetteville State University', domain: 'fsufay.edu' },
  { name: 'Ferris State University', domain: 'ferris.edu' },
  { name: 'Fielding Institute', domain: 'fielding.edu' },
  { name: 'Fisk University', domain: 'fisk.edu' },
  { name: 'Fitchburg State College', domain: 'fsc.edu' },
  {
    name: 'Florida Agricultural and Mechanical University',
    domain: 'famu.edu',
  },
  { name: 'Florida Atlantic University', domain: 'fau.edu' },
  { name: 'Florida Gulf Coast University', domain: 'fgcu.edu' },
  { name: 'Florida Institute of Technology', domain: 'fit.edu' },
  { name: 'Florida International University', domain: 'fiu.edu' },
  { name: 'Florida State University', domain: 'fsu.edu' },
  { name: 'Fontbonne College', domain: 'fontbonne.edu' },
  { name: 'Fordham University', domain: 'fordham.edu' },
  { name: 'Fort Hays State University', domain: 'fhsu.edu' },
  { name: 'Fort Lewis College', domain: 'fortlewis.edu' },
  { name: 'Franklin and Marshall College', domain: 'fandm.edu' },
  { name: 'Franklin Pierce Law Center', domain: 'fplc.edu' },
  { name: 'Franklin University', domain: 'franklin.edu' },
  { name: 'Fresno Pacific University', domain: 'fresno.edu' },
  { name: 'Friends University', domain: 'friends.edu' },
  { name: 'Frostburg State University', domain: 'fsu.umd.edu' },
  { name: 'Fuller Theological Seminary', domain: 'fuller.edu' },
  { name: 'Furman University', domain: 'furman.edu' },
  { name: 'Gallaudet University', domain: 'gallaudet.edu' },
  { name: 'Gannon University', domain: 'gannon.edu' },
  { name: 'Geneva College', domain: 'geneva.edu' },
  { name: 'George Fox College', domain: 'gfc.edu' },
  { name: 'George Mason University', domain: 'gmu.edu' },
  { name: 'George Washington University', domain: 'gwu.edu' },
  { name: 'Georgetown University', domain: 'georgetown.edu' },
  { name: 'Georgia College', domain: 'gac.peachnet.edu' },
  { name: 'Georgia Institute of Technology', domain: 'gatech.edu' },
  { name: 'Georgia Southern University', domain: 'gasou.edu' },
  { name: 'Georgia Southwestern College', domain: 'gsw.peachnet.edu' },
  { name: 'Georgia State University', domain: 'gsu.edu' },
  { name: 'Georgian Court College', domain: 'georgian.edu' },
  { name: 'Gettysburg College', domain: 'gettysburg.edu' },
  { name: 'GMI Engineering and Management Institute', domain: 'gmi.edu' },
  { name: 'Golden Gate University', domain: 'ggu.edu' },
  { name: 'Goldey-Beacom College', domain: 'gbc.edu' },
  { name: 'Gonzaga University', domain: 'gonzaga.edu' },
  { name: 'Goshen College', domain: 'goshen.edu' },
  { name: 'Goucher College', domain: 'goucher.edu' },
  { name: 'Governors State University', domain: 'bgu.edu' },
  { name: 'Grace College', domain: 'grace.edu' },
  { name: 'Graceland College', domain: 'graceland.edu' },
  { name: 'Grand Valley State University', domain: 'gvsu.edu' },
  { name: 'Greenleaf University', domain: 'greenleaf.edu' },
  { name: 'Grinnell College', domain: 'grin.edu' },
  { name: 'Guilford College', domain: 'guilford.edu' },
  { name: 'Gustavus Adolphus College', domain: 'gac.edu' },
  { name: 'Hamilton College', domain: 'hamilton.edu' },
  { name: 'Hamline University', domain: 'hamline.edu' },
  { name: 'Hampden-Sydney College', domain: 'hsc.edu' },
  { name: 'Hampshire College', domain: 'hampshire.edu' },
  { name: 'Hampton University', domain: 'hamptonu.edu' },
  { name: 'Hanover College', domain: 'hanover.edu' },
  { name: 'Harding University', domain: 'harding.edu' },
  { name: 'Hartwick College', domain: 'hartwick.edu' },
  { name: 'Harvard University', domain: 'harvard.edu' },
  { name: 'Harvey Mudd College', domain: 'hmc.edu' },
  { name: 'Haskell Indian Nations University', domain: 'haskell.edu' },
  { name: 'Hastings College', domain: 'hastings.edu' },
  { name: 'Haverford College in Pennsylvania', domain: 'haverford.edu' },
  { name: 'Hawaii Pacific University', domain: 'hpu.edu' },
  { name: 'Heidelberg College', domain: 'heidelberg.edu' },
  { name: 'Hendrix College', domain: 'hendrix.edu' },
  { name: 'Hesston College', domain: 'hesston.edu' },
  { name: 'High Point University', domain: 'highpoint.edu' },
  { name: 'Hillsdale College', domain: 'hillsdale.edu' },
  { name: 'Hiram College', domain: 'hiram.edu' },
  { name: 'Hobart and William Smith Colleges', domain: 'hws.edu' },
  { name: 'Hofstra University', domain: 'hofstra.edu' },
  { name: 'Hollins College', domain: 'hollins.edu' },
  { name: 'Holy Cross College', domain: 'holycross.edu' },
  { name: 'Hood College', domain: 'hood.edu' },
  { name: 'Hope College', domain: 'hope.edu' },
  { name: 'Howard University', domain: 'howard.edu' },
  { name: 'Humboldt State University', domain: 'humboldt.edu' },
  { name: 'Hunter College', domain: 'hunter.cuny.edu' },
  { name: 'Huntingdon College', domain: 'huntingdon.edu' },
  { name: 'Huntington College', domain: 'huntcol.edu' },
  { name: 'ICI University', domain: 'ici.edu' },
  { name: 'Idaho State University', domain: 'isu.edu' },
  { name: 'Illinois Benedictine College', domain: 'ibc.edu' },
  { name: 'Illinois Institute of Technology', domain: 'iit.edu' },
  { name: 'Illinois State University', domain: 'ilstu.edu' },
  { name: 'Incarnate Word College', domain: 'iwctx.edu' },
  { name: 'Indiana Institute of Technology', domain: 'indtech.edu' },
  { name: 'Indiana State University', domain: 'indstate.edu' },
  { name: 'Indiana University System', domain: 'indiana.edu' },
  {
    name: 'Indiana University/Purdue University at Columbus',
    domain: 'columbus.iupui.edu',
  },
  {
    name: 'Indiana University/Purdue University at Fort Wayne',
    domain: 'ipfw.indiana.edu',
  },
  {
    name: 'Indiana University/Purdue University at Indianapolis',
    domain: 'iupui.edu',
  },
  { name: 'Indiana University at Bloomington', domain: 'indiana.edu' },
  { name: 'Indiana University at South Bend', domain: 'iusb.indiana.edu' },
  { name: 'Indiana University of Pennsylvania', domain: 'iup.edu' },
  {
    name: 'Indiana University Southeast at New Albany',
    domain: 'ius.indiana.edu',
  },
  { name: 'Indiana Wesleyan University, Marion', domain: 'indwes.edu' },
  {
    name: 'Inter American University of Puerto Rico Metropolitan Campus',
    domain: 'metro.inter.edu',
  },
  { name: 'Iona College', domain: 'iona.edu' },
  { name: 'Iowa State University', domain: 'iastate.edu' },
  { name: 'Ithaca College', domain: 'ithaca.edu' },
  { name: 'Jackson State University', domain: 'jsums.edu' },
  { name: 'Jacksonville University', domain: 'ju.edu' },
  { name: 'Jacksonville State University', domain: 'jsu.edu' },
  { name: 'James Madison University', domain: 'jmu.edu' },
  { name: 'Jamestown College', domain: 'jc.edu' },
  { name: 'The Jewish Theological Seminary', domain: 'jtsa.edu' },
  { name: 'John Brown University', domain: 'jbu.edu' },
  { name: 'John F. Kennedy University', domain: 'jfku.edu' },
  { name: 'Johns Hopkins University', domain: 'jhu.edu' },
  { name: 'Johnson Bible College', domain: 'jbc.edu' },
  { name: 'Johnson C. Smith University', domain: 'jcsu.edu' },
  { name: 'Johnson & Wales University', domain: 'jwu.edu' },
  { name: 'Johnson & Wales University-Charleston', domain: '' },
  { name: 'Jones College', domain: 'jones.edu' },
  { name: 'Judson College', domain: 'judson.edu' },
  { name: 'Juniata College', domain: 'juniata.edu' },
  { name: 'Kalamazoo College', domain: 'kzoo.edu' },
  { name: 'Kansas State University', domain: 'ksu.edu' },
  { name: 'Kansas Wesleyan University', domain: 'kwu.edu' },
  { name: 'Kean College', domain: 'kean.edu' },
  { name: 'Keene State College', domain: 'keene.edu' },
  { name: 'Kent State University', domain: 'kent.edu' },
  { name: 'Kenyon College', domain: 'kenyon.edu' },
  { name: "King's College", domain: 'kings.edu' },
  { name: 'Knox College', domain: 'knox.edu' },
  { name: 'Kutztown University of Pennsylvania', domain: 'kutztown.edu' },
  { name: 'La Sierra University', domain: 'lasierra.edu' },
  { name: 'LaGrange College', domain: 'lgc.peachnet.edu' },
  { name: 'Lafayette College', domain: 'lafayette.edu' },
  { name: 'Lake Forest College', domain: 'lfc.edu' },
  { name: 'Lake Superior State University', domain: 'lssu.edu' },
  { name: 'Lamar University', domain: 'lamar.edu' },
  { name: 'Langston University', domain: 'lunet.edu' },
  { name: 'LaSalle University', domain: 'lasalle.edu' },
  { name: 'Lawrence University', domain: 'lawrence.edu' },
  { name: 'Lawrence Technological University', domain: 'ltu.edu' },
  { name: 'Lebanon Valley College', domain: 'lvc.edu' },
  { name: 'Lehigh University', domain: 'lehigh.edu' },
  { name: 'Le Moyne College', domain: 'lemoyne.edu' },
  { name: 'Lenoir-Rhyne College', domain: 'lrc.edu' },
  { name: 'LeTourneau University', domain: 'letu.edu' },
  { name: 'Lewis & Clark College', domain: 'lclark.edu' },
  { name: 'Lewis-Clark State College', domain: 'lcsc.edu' },
  { name: 'Lewis University', domain: 'lewisu.edu' },
  { name: 'Liberty University', domain: 'liberty.edu' },
  { name: 'Lincoln University', domain: 'lincoln.edu' },
  { name: 'Linfield College', domain: 'linfield.edu' },
  { name: 'Lock Haven University of Pennsylvania', domain: 'lhup.edu' },
  { name: 'Loma Linda University', domain: 'llu.edu' },
  { name: 'Long Island University', domain: 'liunet.edu' },
  { name: 'Longwood College', domain: 'lwc.edu' },
  { name: 'Loras College', domain: 'loras.edu' },
  { name: 'Louisiana College', domain: 'lacollege.edu' },
  { name: 'Louisiana State University', domain: 'lsu.edu' },
  { name: 'Louisiana State University at Alexandria', domain: 'lsua.edu' },
  { name: 'Louisiana Tech University', domain: 'latech.edu' },
  { name: 'Loyola College', domain: 'loyola.edu' },
  { name: 'Loyola Marymount University', domain: 'lmu.edu' },
  { name: 'Loyola University Chicago', domain: 'luc.edu' },
  { name: 'Luther College', domain: 'luther.edu' },
  { name: 'Luther Seminary', domain: 'luthersem.edu' },
  { name: 'Lycoming College', domain: 'lycoming.edu' },
  { name: 'Lynchburg College', domain: 'lynchburg.edu' },
  { name: 'Lyndon State College', domain: 'lsc.vsc.edu' },
  { name: 'Lyon College', domain: 'lyon.edu' },
  { name: 'Macalester College', domain: 'macalstr.edu' },
  { name: 'Maharishi University of Management', domain: 'mum.edu' },
  { name: 'Maine Maritime Academy', domain: '' },
  { name: 'Malone College', domain: 'malone.edu' },
  { name: 'Manhattan College', domain: 'mancol.edu' },
  { name: 'Mankato State University', domain: 'mankato.msus.edu' },
  { name: 'Mansfield University of Pennsylvania', domain: 'mnsfld.edu' },
  { name: 'Marietta College', domain: 'marietta.edu' },
  { name: 'Marist College', domain: 'marist.edu' },
  { name: 'Marlboro College', domain: 'marlboro.edu' },
  { name: 'Marquette University', domain: 'mu.edu' },
  { name: 'Marshall University', domain: 'marshall.edu' },
  { name: 'Mary Baldwin College', domain: 'mbc.edu' },
  { name: 'Marymount College', domain: 'marymt.edu' },
  { name: 'Marymount University', domain: 'marymount.edu' },
  { name: 'Mary Washington College', domain: 'mwc.edu' },
  { name: 'Massachusetts Institute of Technology', domain: 'mit.edu' },
  { name: 'McMurry University', domain: 'mcm.acu.edu' },
  { name: 'McNeese State University', domain: 'mcneese.edu' },
  { name: 'Medical College of Georgia', domain: 'mcg.edu' },
  { name: 'Medical College of Wisconsin', domain: 'mcw.edu' },
  { name: 'Mercer University', domain: 'mercer.peachnet.edu' },
  { name: 'Mercyhurst College', domain: 'mercy.edu' },
  { name: 'Meredith College', domain: 'meredith.edu' },
  { name: 'Messiah College', domain: 'messiah.edu' },
  { name: 'Metropolitan State College of Denver', domain: 'mscd.edu' },
  { name: 'Metropolitan State University', domain: 'metro.msus.edu' },
  { name: 'Miami Christian University', domain: 'mcu.edu' },
  { name: 'Miami University of Ohio', domain: 'muohio.edu' },
  { name: 'Michigan State University', domain: 'msu.edu' },
  { name: 'Michigan Technological University', domain: 'mtu.edu' },
  { name: 'Mid-America Nazarene College', domain: 'manc.edu' },
  { name: 'Middlebury College', domain: 'middlebury.edu' },
  { name: 'Middle Georgia College', domain: 'mgc.peachnet.edu' },
  { name: 'Middle Tennessee State University', domain: 'mtsu.edu' },
  { name: 'Midwestern State University', domain: 'mwsu.edu' },
  { name: 'Millersville University of Pennsylvania', domain: 'millersv.edu' },
  { name: 'Milligan College', domain: 'milligan-college.tn.us' },
  { name: 'Millikin University', domain: 'millikin.edu' },
  { name: 'Millsaps College', domain: 'millsaps.edu' },
  { name: 'Milwaukee School of Engineering', domain: 'msoe.edu' },
  { name: 'Minot State University', domain: 'misu.nodak.edu' },
  { name: 'Minneapolis College of Art and Design', domain: 'mcad.edu' },
  { name: 'Mississippi College', domain: 'mc.edu' },
  { name: 'Mississippi State University', domain: 'msstate.edu' },
  { name: 'Mississippi University for Women', domain: 'muw.edu' },
  { name: 'Missouri Southern State College', domain: 'mssc.edu' },
  { name: 'Missouri Western State College', domain: 'mwsc.edu' },
  { name: 'Molloy College', domain: 'molloy.edu' },
  { name: 'Monmouth College', domain: 'monm.edu' },
  { name: 'Monmouth University', domain: 'monmouth.edu' },
  { name: 'Montana State University-Billings', domain: 'msubillings.edu' },
  { name: 'Montana State University-Bozeman', domain: 'montana.edu' },
  { name: 'Montana State University-Northern', domain: 'nmclites.edu' },
  { name: 'Montana Tech', domain: 'mtech.edu' },
  { name: 'Montclair State University', domain: 'montclair.edu' },
  { name: 'Montreat College', domain: 'montreat.edu' },
  { name: 'Moravian College', domain: 'moravian.edu' },
  { name: 'Moorhead State University', domain: 'moorhead.msus.edu' },
  { name: 'Morehouse College', domain: '' },
  { name: 'Morgan State University', domain: 'morgan.edu' },
  { name: 'Mount Senario College', domain: 'mscfs.edu' },
  { name: 'Mount Holyoke College', domain: 'mtholyoke.edu' },
  { name: 'Mount Saint Joseph College', domain: 'msjnet.edu' },
  { name: 'Mount Saint Mary College', domain: 'msmc.edu' },
  { name: 'Mount Union College', domain: 'muc.edu' },
  { name: 'Murray State University', domain: 'mursuky.edu' },
  { name: 'Muskingum College', domain: 'muskingum.edu' },
  { name: 'National Defense University', domain: 'ndu.edu' },
  { name: 'National-Louis University', domain: 'nl.edu' },
  { name: 'National Technological University', domain: 'ntu.edu' },
  { name: 'National University', domain: 'nu.edu' },
  { name: 'Naval Postgraduate School', domain: 'nps.navy.mil' },
  { name: 'Nazareth College', domain: 'naz.edu' },
  { name: 'Newberry College', domain: 'newberry.edu' },
  { name: 'New England Institute of Technology', domain: '' },
  { name: 'New College of California', domain: 'newcollege.edu' },
  { name: 'New Hampshire College', domain: 'nhc.edu' },
  { name: 'New Jersey Institute of Technology', domain: 'njit.edu' },
  { name: 'New Mexico Highlands University', domain: 'nmhu.edu' },
  { name: 'New Mexico Institute of Mining & Technology', domain: 'nmt.edu' },
  { name: 'New Mexico State University', domain: 'nmsu.edu' },
  { name: 'New York Institute of Technology', domain: 'nyit.edu' },
  { name: 'New York University', domain: 'nyu.edu' },
  { name: 'Niagara University', domain: 'niagara.edu' },
  { name: 'Nicholls State University', domain: 'nich.edu' },
  { name: 'Norfolk State University', domain: 'nsu.edu' },
  { name: 'North Adams State College', domain: 'nasc.mass.edu' },
  { name: 'North Carolina Central University', domain: 'nccu.edu' },
  { name: 'North Carolina A&T State University', domain: 'ncat.edu' },
  { name: 'North Carolina State University', domain: 'ncsu.edu' },
  { name: 'North Carolina Wesleyan College', domain: 'ncwc.edu' },
  { name: 'North Central Bible College', domain: 'ncbc.edu' },
  { name: 'North Dakota State University', domain: 'ndsu.nodak.edu' },
  { name: 'Northland College', domain: 'northland.edu' },
  { name: 'North Park College and Theological Seminary', domain: 'npcts.edu' },
  { name: 'Northeastern Illinois University', domain: '' },
  { name: 'Northeastern Louisiana University', domain: 'nlu.edu' },
  { name: 'Northeastern State University', domain: 'nsuok.edu' },
  { name: 'Northeastern University', domain: 'northeastern.edu' },
  { name: 'Northern Arizona University', domain: 'nau.edu' },
  { name: 'Northern Illinois University', domain: 'niu.edu' },
  { name: 'Northern Kentucky University', domain: 'nku.edu' },
  { name: 'Northern Michigan University', domain: 'nmu.edu' },
  { name: 'Northern State University', domain: 'northern.edu' },
  { name: 'Northwest Missouri State University', domain: 'nwmissouri.edu' },
  { name: 'Northwest Nazarene College', domain: 'nnc.edu' },
  { name: 'Northwestern College of Iowa', domain: 'nwciowa.edu' },
  { name: 'Northwestern State University', domain: 'nsula.edu' },
  { name: 'Northwestern University', domain: 'nwu.edu' },
  { name: 'Norwich University', domain: 'norwich.edu' },
  { name: 'Nova Southeastern University', domain: 'nova.edu' },
  { name: 'Nyack College', domain: 'nyack.edu' },
  { name: 'Oakland University', domain: 'oakland.edu' },
  { name: 'Oberlin College', domain: 'oberlin.edu' },
  { name: 'Occidental College', domain: 'oxy.edu' },
  { name: 'Oglethorpe University', domain: 'oglethorpe.edu' },
  { name: 'Ohio Dominican College', domain: 'odc.edu' },
  { name: 'Ohio Northern University', domain: 'onu.edu' },
  { name: 'Ohio State University', domain: 'osu.edu' },
  { name: 'Ohio University', domain: 'ohiou.edu' },
  { name: 'Ohio Wesleyan University', domain: 'owu.edu' },
  { name: 'Oklahoma Baptist University', domain: 'okbu.edu' },
  { name: 'Oklahoma Christian University', domain: 'oc.edu' },
  { name: 'Oklahoma City University', domain: 'okcu.edu' },
  { name: 'Oklahoma State University', domain: 'okstate.edu' },
  { name: 'Old Dominion University', domain: 'odu.edu' },
  { name: 'Olivet College', domain: 'olivet.edu' },
  { name: 'Olivet Nazarene University', domain: 'olivet.edu' },
  { name: 'Oral Roberts University', domain: 'oru.edu' },
  {
    name: 'Oregon Graduate Institute of Science and Technology',
    domain: 'ogi.edu',
  },
  { name: 'Oregon Health Sciences University', domain: 'ohsu.edu' },
  { name: 'Oregon Institute of Technology', domain: 'oit.edu' },
  { name: 'Oregon State University', domain: 'oregonstate.edu' },
  { name: 'Otis College of Art and Design', domain: 'otisart.edu' },
  { name: 'Ottawa University', domain: 'ottawa.edu' },
  { name: 'Otterbein College', domain: 'otterbein.edu' },
  { name: 'Ouachita Baptist University', domain: 'obu.edu' },
  { name: 'Our Lady of the Lake University', domain: 'ollusa.edu' },
  { name: 'Pace University', domain: 'pace.edu' },
  { name: 'Pacific Lutheran University', domain: 'plu.edu' },
  { name: 'Pacific Union College', domain: 'puc.edu' },
  { name: 'Pacific University', domain: 'pacificu.edu' },
  { name: 'Palm Beach Atlantic College', domain: 'pba.edu' },
  { name: 'Park College', domain: 'park.edu' },
  { name: 'Parsons School of Design', domain: 'newschool.edu' },
  { name: 'Paul Quinn College', domain: 'pqc.edu' },
  { name: 'Peabody College', domain: 'vanderbilt.edu' },
  { name: 'Pennsylvania State University', domain: 'psu.edu' },
  { name: 'Pepperdine University', domain: 'pepperdine.edu' },
  { name: 'Pfeiffer University', domain: 'pfeiffer.edu' },
  { name: 'Philadelphia College of Bible', domain: 'pcb.edu' },
  { name: 'Philander Smith College', domain: 'philander.edu' },
  { name: 'Phillips University', domain: 'phillips.edu' },
  { name: 'Piedmont College', domain: 'piedmont.edu' },
  { name: 'Pillsbury Baptist Bible College', domain: 'pillsbury.edu' },
  { name: 'Pine Manor College', domain: 'pmc.edu' },
  { name: 'Pittsburg State University', domain: 'pittstate.edu' },
  { name: 'Pitzer College', domain: 'pitzer.edu' },
  { name: 'Point Loma Nazarene College', domain: 'pointloma.edu' },
  { name: 'Point Park College', domain: 'pointpark.edu' },
  { name: 'Polytechnic University of New York', domain: 'poly.edu' },
  { name: 'Pomona College', domain: 'pomona.edu' },
  { name: 'Portland State University', domain: 'pdx.edu' },
  { name: 'Post University of Waterbury', domain: 'post.edu' },
  { name: 'Prairie View A&M University', domain: 'pvamu.edu' },
  { name: 'Pratt Institute', domain: 'pratt.edu' },
  { name: 'Presbyterian College', domain: 'presby.edu' },
  { name: 'Princeton University', domain: 'princeton.edu' },
  { name: 'Principia College', domain: 'prin.edu' },
  { name: 'Providence College', domain: 'providence.edu' },
  { name: 'Purdue University', domain: 'purdue.edu' },
  { name: 'Purdue University Calumet', domain: 'calumet.purdue.edu' },
  { name: 'Purdue University North Central', domain: 'pnc.edu' },
  { name: 'Queens College', domain: 'qc.edu' },
  { name: 'Quincy University', domain: 'quincy.edu' },
  { name: 'Quinnipiac College', domain: 'quinnipiac.edu' },
  { name: 'Radford University', domain: 'radford.edu' },
  { name: 'Ramapo College of New Jersey', domain: 'ramapo.edu' },
  { name: 'Randolph-Macon College', domain: 'rmc.edu' },
  { name: "Randolph-Macon Woman's College", domain: 'rmwc.edu' },
  { name: 'Reed College', domain: 'reed.edu' },
  { name: 'Regent International University', domain: 'regent.edu' },
  { name: 'Regent University', domain: 'regent.edu' },
  { name: 'Regis College', domain: 'regiscollege.edu' },
  { name: 'Rensselaer Polytechnic Institute', domain: 'rpi.edu' },
  { name: 'Rhode Island College', domain: 'ric.edu' },
  { name: 'Rhode Island School of Design', domain: 'risd.edu' },
  { name: 'Rhodes College', domain: 'rhodes.edu' },
  { name: 'Rice University', domain: 'rice.edu' },
  { name: 'Richard Stockton College', domain: 'stockton.edu' },
  { name: 'Rider University', domain: 'rider.edu' },
  { name: 'Ripon College', domain: 'ripon.edu' },
  { name: 'Rivier College', domain: 'rivier.edu' },
  { name: 'Roanoke College', domain: 'roanoke.edu' },
  { name: 'Robert Morris College', domain: 'rmc.edu' },
  { name: 'Rochester Institute of Technology', domain: 'rit.edu' },
  { name: 'Rockford College', domain: 'rockford.edu' },
  { name: 'Rockhurst College', domain: 'rockhurst.edu' },
  { name: 'Rocky Mountain College', domain: 'rocky.edu' },
  { name: 'Roger Williams University', domain: 'rwu.edu' },
  { name: 'Rollins College', domain: 'rollins.edu' },
  { name: 'Roosevelt University', domain: 'roosevelt.edu' },
  { name: 'Rose-Hulman Institute of Technology', domain: 'rose-hulman.edu' },
  { name: 'Rowan College', domain: 'rowan.edu' },
  { name: 'Rutgers University', domain: 'rutgers.edu' },
  { name: 'S', domain: '' }, // Domain is missing
  { name: 'Sacred Heart University', domain: 'sacredheart.edu' },
  { name: 'Saint Ambrose University', domain: 'sau.edu' },
  { name: 'Saint Anselm College', domain: 'anselm.edu' },
  { name: 'Saint Cloud State University', domain: 'stcloudstate.edu' },
  { name: "Saint Edward's University", domain: 'stedwards.edu' },
  { name: 'Saint Francis College', domain: 'sfc.edu' },
  { name: 'Saint Francis College of Indiana', domain: 'sfc.edu' },
  { name: 'Saint John Fisher College', domain: 'sjfc.edu' },
  { name: "Saint John's University", domain: 'csbsju.edu' },
  { name: "Saint John's University", domain: 'stjohns.edu' },
  { name: 'Saint Joseph College', domain: 'sjc.edu' },
  { name: 'Saint Joseph College of Maine', domain: 'sjcme.edu' },
  { name: 'Saint Josephs College of Indiana', domain: 'sjc.edu' },
  { name: 'Saint Lawrence University', domain: 'stlawu.edu' },
  { name: 'Saint Leo College', domain: 'saintleo.edu' },
  { name: 'Saint Louis University', domain: 'slu.edu' },
  { name: 'Saint Martins College', domain: 'stmartin.edu' },
  { name: 'Saint Mary College', domain: 'stmary.edu' },
  { name: 'Saint Mary-of-the-Woods College', domain: 'smwc.edu' },
  { name: 'Saint Marys College of California', domain: 'stmarys-ca.edu' },
  { name: 'Saint Marys College of Indiana', domain: 'stmarys.edu' },
  { name: 'Saint Marys University of Minnesota', domain: 'smumn.edu' },
  { name: "Saint Mary's College", domain: 'smcvt.edu' },
  { name: "Saint Mary's College of Maryland", domain: 'smcm.edu' },
  { name: "Saint Michael's College", domain: 'smcvt.edu' },
  { name: "Saint Michael's College", domain: 'smcvt.edu' },
  { name: 'Saint Olaf College', domain: 'stolaf.edu' },
  { name: 'Saint Pauls College', domain: 'st-pauls.edu' },
  { name: 'Saint Peters College', domain: 'spc.edu' },
  { name: 'Saint Thomas Aquinas College', domain: 'stac.edu' },
  { name: 'Saint Thomas University', domain: 'stu.edu' },
  { name: 'Saint Vincent College', domain: 'stvincent.edu' },
  { name: 'Saint Xavier University', domain: 'sxu.edu' },
  { name: 'Salem College', domain: 'salem.edu' },
  { name: 'Salem State College', domain: 'salem.mass.edu' },
  { name: 'Salisbury State University', domain: 'salisbury.edu' },
  { name: 'Salve Regina University', domain: 'salve.edu' },
  { name: 'Samford University', domain: 'samford.edu' },
  { name: 'San Diego State University', domain: 'sdsu.edu' },
  { name: 'San Francisco State University', domain: 'sfsu.edu' },
  { name: 'San Jose State University', domain: 'sjsu.edu' },
  { name: 'Santa Clara University', domain: 'scu.edu' },
  { name: 'Sarah Lawrence College', domain: 'slc.edu' },
  { name: 'Savannah College of Art and Design', domain: 'scad.edu' },
  { name: 'Savannah State University', domain: 'savstate.edu' },
  { name: 'Schiller International University', domain: 'schiller.edu' },
  { name: 'School of the Art Institute of Chicago', domain: 'artic.edu' },
  { name: 'School of Visual Arts', domain: 'sva.edu' },
  { name: 'Schreiner College', domain: 'schreiner.edu' },
  { name: 'Scripps College', domain: 'scrippscol.edu' },
  { name: 'Seattle Pacific University', domain: 'spu.edu' },
  { name: 'Seattle University', domain: 'seattleu.edu' },
  { name: 'Seton Hall University', domain: 'shu.edu' },
  { name: 'Shaw University', domain: 'shawu.edu' },
  { name: 'Shenandoah University', domain: 'su.edu' },
  { name: 'Shepherd College', domain: 'shepherd.edu' },
  { name: 'Shippensburg University of Pennsylvania', domain: 'ship.edu' },
  { name: 'Shorter College', domain: 'shorter.edu' },
  { name: 'Siena College', domain: 'siena.edu' },
  { name: 'Sierra Nevada College', domain: 'sierranevada.edu' },
  { name: 'Silver Lake College', domain: 'silver.sl.edu' },
  { name: 'Simmons College', domain: 'simmons.edu' },
  { name: 'Simpson College', domain: 'simpson.edu' },
  { name: 'Sinte Gleska University', domain: 'sinte.edu' },
  { name: 'Skidmore College', domain: 'skidmore.edu' },
  { name: 'Slippery Rock University', domain: 'sru.edu' },
  { name: 'Smith College', domain: 'smith.edu' },
  { name: 'Sonoma State University', domain: 'sonoma.edu' },
  { name: 'South Carolina State University', domain: 'scsu.edu' },
  { name: 'South Dakota School of Mines and Technology', domain: 'sdsmt.edu' },
  { name: 'South Dakota State University', domain: 'sdstate.edu' },
  { name: 'Southeast Missouri State University', domain: 'semo.edu' },
  { name: 'Southeastern Massachusetts University', domain: 'smu.edu' },
  { name: 'Southeastern Oklahoma State University', domain: 'sosu.edu' },
  { name: 'Southeastern University', domain: 'seu.edu' },
  { name: 'Southern Adventist University', domain: 'southern.edu' },
  { name: 'Southern Arkansas University', domain: 'saumag.edu' },
  { name: 'Southern California College', domain: 'sccollege.edu' },
  { name: 'Southern California College of Optometry', domain: 'scco.edu' },
  { name: 'Southern College', domain: 'southerncollege.edu' },
  { name: 'Southern College of Technology', domain: 'sct.edu' },
  {
    name: 'Southern Connecticut State University',
    domain: 'scsu.ctstateu.edu',
  },
  { name: 'Southern Illinois University', domain: 'siu.edu' },
  { name: 'Southern Methodist University', domain: 'smu.edu' },
  { name: 'Southern Nazarene University', domain: 'snu.edu' },
  { name: 'Southern Oregon State College', domain: 'sosc.osshe.edu' },
  { name: 'Southern University and A&M College', domain: 'subr.edu' },
  { name: 'Southern Vermont College', domain: 'svc.edu' },
  { name: 'Southwest Baptist University', domain: 'sbuniv.edu' },
  { name: 'Southwestern Adventist College', domain: 'swac.edu' },
  { name: 'Southwestern Assemblies of God University', domain: 'sagu.edu' },
  { name: 'Southwestern College', domain: 'swc.edu' },
  { name: 'Southwestern College', domain: 'sckans.edu' },
  { name: 'Southwestern College', domain: 'swc.edu' },
  { name: 'Southwestern Oklahoma State University', domain: 'swosu.edu' },
  { name: 'Southwestern University', domain: 'swu.edu' },
  { name: 'Spalding University', domain: 'spalding.edu' },
  { name: 'Spelman College', domain: 'spelman.edu' },
  { name: 'Spring Arbor College', domain: 'arbor.edu' },
  { name: 'Spring Hill College', domain: 'shc.edu' },
  { name: 'Springfield College', domain: 'spfldcol.edu' },
  { name: 'St. Bonaventure University', domain: 'sbu.edu' },
  { name: "St. John's College", domain: 'sjca.edu' },
  { name: 'St. Marys College of California', domain: 'stmarys-ca.edu' },
  { name: 'St. Marys College of Maryland', domain: 'smcm.edu' },
  { name: 'St. Marys University of San Antonio', domain: 'stmarytx.edu' },
  { name: 'St. Olaf College', domain: 'stolaf.edu' },
  { name: 'St. Pauls College', domain: 'st-pauls.edu' },
  { name: 'St. Petersburg Junior College', domain: 'spjc.cc.fl.us' },
  { name: 'St. Thomas Aquinas College', domain: 'stac.edu' },
  { name: 'State University of New York at Albany', domain: 'albany.edu' },
  {
    name: 'State University of New York at Binghamton',
    domain: 'binghamton.edu',
  },
  { name: 'State University of New York at Buffalo', domain: 'buffalo.edu' },
  { name: 'State University of New York at New Paltz', domain: 'newpaltz.edu' },
  { name: 'State University of New York at Oswego', domain: 'oswego.edu' },
  { name: 'State University of New York at Stony Brook', domain: 'sunysb.edu' },
  { name: 'Stetson University', domain: 'stetson.edu' },
  { name: 'Stevens Institute of Technology', domain: 'stevens-tech.edu' },
  { name: 'Stevenson University', domain: 'stevenson.edu' },
  { name: 'Stillman College', domain: 'stillman.edu' },
  { name: 'Stockton College', domain: 'stockton.edu' },
  { name: 'Stonehill College', domain: 'stonehill.edu' },
  { name: 'Strayer University', domain: 'strayer.edu' },
  { name: 'Suffolk University', domain: 'suffolk.edu' },
  { name: 'Sul Ross State University', domain: 'sulross.edu' },
  { name: 'Summit University of Louisiana', domain: 'summitunivofla.edu' },
  { name: 'Susquehanna University', domain: 'susqu.edu' },
  { name: 'Swarthmore College', domain: 'swarthmore.edu' },
  { name: 'Sweet Briar College', domain: 'sbc.edu' },
  { name: 'Syracuse University', domain: 'syr.edu' },
  { name: 'Tabor College', domain: 'tabor.edu' },
  { name: 'Tarleton State University', domain: 'tarleton.edu' },
  { name: 'Taylor University', domain: 'tayloru.edu' },
  { name: 'Temple University', domain: 'temple.edu' },
  { name: 'Tennessee State University', domain: 'tnstate.edu' },
  { name: 'Tennessee Technological University', domain: 'tntech.edu' },
  { name: 'Texas A&M University', domain: 'tamu.edu' },
  { name: 'Texas A&M University-Commerce', domain: 'tamu-commerce.edu' },
  { name: 'Texas A&M University-Corpus Christi', domain: 'tamucc.edu' },
  { name: 'Texas A&M University-Galveston', domain: 'tamug.edu' },
  { name: 'Texas A&M University-Kingsville', domain: 'tamuk.edu' },
  { name: 'Texas A&M University-Texarkana', domain: 'tamut.edu' },
  { name: 'Texas Christian University', domain: 'tcu.edu' },
  { name: 'Texas College', domain: 'texascollege.edu' },
  { name: 'Texas Lutheran College', domain: 'tlu.edu' },
  { name: 'Texas Southern University', domain: 'tsu.edu' },
  { name: 'Texas Tech University', domain: 'ttu.edu' },
  { name: 'Texas Wesleyan University', domain: 'txwesleyan.edu' },
  { name: "Texas Woman's University", domain: 'twu.edu' },
  { name: 'The Citadel', domain: 'citadel.edu' },
  { name: 'The College of Insurance', domain: 'tci.edu' },
  { name: 'The College of New Jersey', domain: 'tcnj.edu' },
  {
    name: 'The Cooper Union for the Advancement of Science and Art',
    domain: 'cooper.edu',
  },
  { name: 'The Masters College', domain: 'masters.edu' },
  {
    name: 'The Richard Stockton College of New Jersey',
    domain: 'stockton.edu',
  },
  { name: 'The Union Institute', domain: 'tui.edu' },
  { name: 'The University of Findlay', domain: 'findlay.edu' },
  { name: 'Thiel College', domain: 'thiel.edu' },
  { name: 'Thomas Aquinas College', domain: 'thomasaquinas.edu' },
  { name: 'Thomas College', domain: 'thomas.edu' },
  { name: 'Thomas Jefferson University', domain: 'tju.edu' },
  { name: 'Thomas More College', domain: 'thomasmore.edu' },
  { name: 'Tiffin University', domain: 'tiffin.edu' },
  { name: 'Toccoa Falls College', domain: 'tfc.edu' },
  { name: 'Towson University', domain: 'towson.edu' },
  { name: 'Transylvania University', domain: 'transy.edu' },
  { name: 'Trevecca Nazarene University', domain: 'trevecca.edu' },
  { name: 'Tri-State University', domain: 'tristate.edu' },
  { name: 'Trinity Christian College', domain: 'trnty.edu' },
  { name: 'Trinity College', domain: 'trincoll.edu' },
  { name: 'Trinity College of Florida', domain: 'trincol.edu' },
  { name: 'Trinity College of Vermont', domain: 'tcvt.edu' },
  { name: 'Trinity University', domain: 'trinity.edu' },
  { name: 'Troy State University', domain: 'troy.edu' },
  { name: 'Troy State University-Dothan', domain: 'troyst.edu' },
  { name: 'Troy State University-Montgomery', domain: 'troym.edu' },
  { name: 'Troy State University-Phenix City', domain: 'trophc.edu' },
  { name: 'Truman State University', domain: 'truman.edu' },
  { name: 'Tufts University', domain: 'tufts.edu' },
  { name: 'Tulane University', domain: 'tulane.edu' },
  { name: 'Tusculum College', domain: 'tusculum.edu' },
  { name: 'Tuskegee University', domain: 'tusk.edu' },
  { name: 'Union College', domain: 'union.edu' },
  { name: 'Union Institute', domain: 'tui.edu' },
  { name: 'Union University', domain: 'uu.edu' },
  { name: 'United States Air Force Academy', domain: 'usafa.af.mil' },
  { name: 'United States Coast Guard Academy', domain: 'cga.edu' },
  { name: 'United States International University', domain: 'usiu.edu' },
  { name: 'United States Merchant Marine Academy', domain: 'usmma.edu' },
  { name: 'United States Military Academy', domain: 'usma.edu' },
  { name: 'United States Naval Academy', domain: 'usna.edu' },
  { name: 'Unity College', domain: 'unity.edu' },
  { name: 'University of Advancing Technology', domain: 'uat.edu' },
  { name: 'University of Akron', domain: 'uakron.edu' },
  { name: 'University of Alabama', domain: 'ua.edu' },
  { name: 'University of Alabama at Birmingham', domain: 'uab.edu' },
  { name: 'University of Alabama at Huntsville', domain: 'uah.edu' },
  { name: 'University of Alaska', domain: 'uaa.alaska.edu' },
  { name: 'University of Alaska-Fairbanks', domain: 'uaf.edu' },
  { name: 'University of Alaska-Southeast', domain: 'uas.alaska.edu' },
  { name: 'University of Arizona', domain: 'arizona.edu' },
  { name: 'University of Arkansas', domain: 'uark.edu' },
  { name: 'University of Arkansas at Little Rock', domain: 'ualr.edu' },
  { name: 'University of Arkansas at Monticello', domain: 'uamont.edu' },
  { name: 'University of Arkansas at Pine Bluff', domain: 'uapb.edu' },
  { name: 'University of Baltimore', domain: 'ubalt.edu' },
  { name: 'University of Bridgeport', domain: 'bridgeport.edu' },
  { name: 'University of California-Berkeley', domain: 'berkeley.edu' },
  { name: 'University of California-Davis', domain: 'ucdavis.edu' },
  {
    name: 'University of California-Hastings College of Law',
    domain: 'uchastings.edu',
  },
  { name: 'University of California-Irvine', domain: 'uci.edu' },
  { name: 'University of California-Los Angeles', domain: 'ucla.edu' },
  { name: 'University of California-Riverside', domain: 'ucr.edu' },
  { name: 'University of California-San Diego', domain: 'ucsd.edu' },
  { name: 'University of California-San Francisco', domain: 'ucsf.edu' },
  { name: 'University of California-Santa Barbara', domain: 'ucsb.edu' },
  { name: 'University of California-Santa Cruz', domain: 'ucsc.edu' },
  { name: 'University of Central Florida', domain: 'ucf.edu' },
  { name: 'University of Charleston', domain: 'uchaswv.edu' },
  { name: 'University of Chicago', domain: 'uchicago.edu' },
  { name: 'University of Cincinnati', domain: 'uc.edu' },
  { name: 'University of Colorado at Boulder', domain: 'colorado.edu' },
  { name: 'University of Colorado at Colorado Springs', domain: 'uccs.edu' },
  { name: 'University of Colorado at Denver', domain: 'cudenver.edu' },
  { name: 'University of Connecticut', domain: 'uconn.edu' },
  { name: 'University of Dallas', domain: 'udallas.edu' },
  { name: 'University of Dayton', domain: 'udayton.edu' },
  { name: 'University of Delaware', domain: 'udel.edu' },
  { name: 'University of Denver', domain: 'du.edu' },
  { name: 'University of Detroit Mercy', domain: 'udmercy.edu' },
  { name: 'University of Dubuque', domain: 'dbq.edu' },
  { name: 'University of Evansville', domain: 'evansville.edu' },
  { name: 'University of Florida', domain: 'ufl.edu' },
  { name: 'University of Georgia', domain: 'uga.edu' },
  { name: 'University of Great Falls', domain: 'ugf.edu' },
  { name: 'University of Hartford', domain: 'hartford.edu' },
  { name: 'University of Hawaii', domain: 'hawaii.edu' },
  { name: 'University of Hawaii-Hilo', domain: 'hilo.hawaii.edu' },
  { name: 'University of Hawaii-Manoa', domain: 'manoa.hawaii.edu' },
  { name: 'University of Houston', domain: 'uh.edu' },
  { name: 'University of Houston-Clear Lake', domain: 'uhcl.edu' },
  { name: 'University of Houston-Downtown', domain: 'uhd.edu' },
  { name: 'University of Idaho', domain: 'uidaho.edu' },
  { name: 'University of Illinois at Chicago', domain: 'uic.edu' },
  { name: 'University of Illinois at Springfield', domain: 'uis.edu' },
  { name: 'University of Illinois at Urbana-Champaign', domain: 'uiuc.edu' },
  { name: 'University of Indianapolis', domain: 'uindy.edu' },
  { name: 'University of Iowa', domain: 'uiowa.edu' },
  { name: 'University of Kansas', domain: 'ku.edu' },
  { name: 'University of Kentucky', domain: 'uky.edu' },
  { name: 'University of La Verne', domain: 'ulaverne.edu' },
  { name: 'University of Louisiana at Lafayette', domain: 'louisiana.edu' },
  { name: 'University of Louisiana at Monroe', domain: 'ulm.edu' },
  { name: 'University of Louisville', domain: 'louisville.edu' },
  { name: 'University of Maine', domain: 'umaine.edu' },
  { name: 'University of Maine at Augusta', domain: 'uma.edu' },
  { name: 'University of Maine at Farmington', domain: 'umf.maine.edu' },
  { name: 'University of Maine at Fort Kent', domain: 'umfk.maine.edu' },
  { name: 'University of Maine at Machias', domain: 'umm.maine.edu' },
  { name: 'University of Maine at Presque Isle', domain: 'umpi.maine.edu' },
  { name: 'University of Mary', domain: 'umary.edu' },
  { name: 'University of Mary Hardin-Baylor', domain: 'umhb.edu' },
  { name: 'University of Maryland at Baltimore', domain: 'umbc.edu' },
  { name: 'University of Maryland at College Park', domain: 'umcp.edu' },
  { name: 'University of Maryland at Eastern Shore', domain: 'umes.edu' },
  { name: 'University of Maryland-Baltimore County', domain: 'umbc.edu' },
  { name: 'University of Massachusetts at Amherst', domain: 'umass.edu' },
  { name: 'University of Massachusetts at Boston', domain: 'umb.edu' },
  { name: 'University of Massachusetts at Dartmouth', domain: 'umassd.edu' },
  { name: 'University of Massachusetts at Lowell', domain: 'uml.edu' },
  {
    name: 'University of Medicine and Dentistry of New Jersey',
    domain: 'umdnj.edu',
  },
  { name: 'University of Memphis', domain: 'memphis.edu' },
  { name: 'University of Miami', domain: 'miami.edu' },
  { name: 'University of Michigan', domain: 'umich.edu' },
  { name: 'University of Michigan-Dearborn', domain: 'umd.umich.edu' },
  { name: 'University of Michigan-Flint', domain: 'umf.umich.edu' },
  { name: 'University of Minnesota', domain: 'umn.edu' },
  { name: 'University of Mississippi', domain: 'olemiss.edu' },
  { name: 'University of Missouri', domain: 'missouri.edu' },
  { name: 'University of Missouri-Kansas City', domain: 'umkc.edu' },
  { name: 'University of Missouri-Rolla', domain: 'umr.edu' },
  { name: 'University of Missouri-St. Louis', domain: 'umsl.edu' },
  { name: 'University of Mobile', domain: 'umobile.edu' },
  { name: 'University of Montevallo', domain: 'montevallo.edu' },
  { name: 'University of Nebraska', domain: 'unl.edu' },
  { name: 'University of Nebraska-Kearney', domain: 'unk.edu' },
  { name: 'University of Nebraska-Lincoln', domain: 'unl.edu' },
  { name: 'University of Nebraska-Omaha', domain: 'unomaha.edu' },
  { name: 'University of Nevada-Las Vegas', domain: 'unlv.edu' },
  { name: 'University of Nevada-Reno', domain: 'unr.edu' },
  { name: 'University of New England', domain: 'une.edu' },
  { name: 'University of New Hampshire', domain: 'unh.edu' },
  { name: 'University of New Haven', domain: 'unh.edu' },
  { name: 'University of New Mexico', domain: 'unm.edu' },
  { name: 'University of New Orleans', domain: 'uno.edu' },
  { name: 'University of North Alabama', domain: 'una.edu' },
  { name: 'University of North Carolina', domain: 'unc.edu' },
  { name: 'University of North Carolina at Asheville', domain: 'unca.edu' },
  { name: 'University of North Carolina at Chapel Hill', domain: 'unc.edu' },
  { name: 'University of North Carolina at Charlotte', domain: 'uncc.edu' },
  { name: 'University of North Carolina at Greensboro', domain: 'uncg.edu' },
  { name: 'University of North Carolina at Wilmington', domain: 'uncw.edu' },
  { name: 'University of North Dakota', domain: 'und.nodak.edu' },
  { name: 'University of North Florida', domain: 'unf.edu' },
  { name: 'University of North Texas', domain: 'unt.edu' },
  { name: 'University of Northern Colorado', domain: 'unco.edu' },
  { name: 'University of Northern Iowa', domain: 'uni.edu' },
  { name: 'University of Notre Dame', domain: 'nd.edu' },
  { name: 'University of Oklahoma', domain: 'ou.edu' },
  { name: 'University of Oregon', domain: 'uoregon.edu' },
  { name: 'University of Pennsylvania', domain: 'upenn.edu' },
  { name: 'University of Pittsburgh', domain: 'pitt.edu' },
  { name: 'University of Portland', domain: 'uport.edu' },
  { name: 'University of Puget Sound', domain: 'ups.edu' },
  { name: 'University of Redlands', domain: 'redlands.edu' },
  { name: 'University of Rhode Island', domain: 'uri.edu' },
  { name: 'University of Richmond', domain: 'richmond.edu' },
  { name: 'University of Rio Grande', domain: 'rio.edu' },
  { name: 'University of Rochester', domain: 'rochester.edu' },
  { name: 'University of Saint Mary', domain: 'stmary.edu' },
  { name: 'University of Saint Mary of the Lake', domain: 'usml.edu' },
  { name: 'University of San Diego', domain: 'sandiego.edu' },
  { name: 'University of San Francisco', domain: 'usfca.edu' },
  { name: 'University of Science and Arts of Oklahoma', domain: 'usao.edu' },
  { name: 'University of Scranton', domain: 'uofs.edu' },
  { name: 'University of Sioux Falls', domain: 'usf.edu' },
  { name: 'University of South Alabama', domain: 'southalabama.edu' },
  { name: 'University of South Carolina', domain: 'sc.edu' },
  {
    name: 'University of South Carolina-Spartanburg',
    domain: 'usc.upstate.edu',
  },
  { name: 'University of South Dakota', domain: 'usd.edu' },
  { name: 'University of South Florida', domain: 'usf.edu' },
  { name: 'University of Southern California', domain: 'usc.edu' },
  { name: 'University of Southern Indiana', domain: 'usi.edu' },
  { name: 'University of Southern Maine', domain: 'usm.maine.edu' },
  { name: 'University of Southern Mississippi', domain: 'usm.edu' },
  { name: 'University of St. Thomas', domain: 'ust.edu' },
  { name: 'University of Tampa', domain: 'utampa.edu' },
  { name: 'University of Tennessee', domain: 'utk.edu' },
  { name: 'University of Tennessee at Chattanooga', domain: 'utc.edu' },
  { name: 'University of Tennessee at Martin', domain: 'utm.edu' },
  {
    name: 'University of Tennessee Health Science Center',
    domain: 'utmem.edu',
  },
  { name: 'University of Texas', domain: 'utexas.edu' },
  { name: 'University of Texas at Arlington', domain: 'uta.edu' },
  { name: 'University of Texas at Austin', domain: 'utexas.edu' },
  { name: 'University of Texas at Brownsville', domain: 'utb.edu' },
  { name: 'University of Texas at Dallas', domain: 'utdallas.edu' },
  { name: 'University of Texas at El Paso', domain: 'utep.edu' },
  { name: 'University of Texas at San Antonio', domain: 'utsa.edu' },
  {
    name: 'University of Texas Health Science Center at Houston',
    domain: 'uth.tmc.edu',
  },
  {
    name: 'University of Texas Health Science Center at San Antonio',
    domain: 'uthscsa.edu',
  },
  {
    name: 'University of Texas Medical Branch at Galveston',
    domain: 'utmb.edu',
  },
  { name: 'University of the Arts', domain: 'uarts.edu' },
  { name: 'University of the District of Columbia', domain: 'udc.edu' },
  { name: 'University of the Incarnate Word', domain: 'incarnateword.edu' },
  { name: 'University of the Ozarks', domain: 'ozarks.edu' },
  { name: 'University of the Pacific', domain: 'pacific.edu' },
  { name: 'University of the Redlands', domain: 'redlands.edu' },
  { name: 'University of the Sciences in Philadelphia', domain: 'usip.edu' },
  { name: 'University of the South', domain: 'sewanee.edu' },
  { name: 'University of the South Pacific', domain: 'usp.ac.fj' },
  { name: 'University of the Southwest', domain: 'usw.edu' },
  { name: 'University of Toledo', domain: 'utoledo.edu' },
  { name: 'University of Tulsa', domain: 'utulsa.edu' },
  { name: 'University of Utah', domain: 'utah.edu' },
  { name: 'University of Vermont', domain: 'uvm.edu' },
  { name: 'University of Virginia', domain: 'virginia.edu' },
  { name: 'University of Virginia-Main Campus', domain: 'virginia.edu' },
  { name: 'University of Virginia-Wise', domain: 'uvawise.edu' },
  { name: 'University of Washington', domain: 'washington.edu' },
  { name: 'University of West Alabama', domain: 'uwa.edu' },
  { name: 'University of West Florida', domain: 'uwf.edu' },
  { name: 'University of West Los Angeles', domain: 'uwla.edu' },
  { name: 'University of West Virginia', domain: 'wvu.edu' },
  {
    name: 'University of West Virginia Institute of Technology',
    domain: 'wvutech.edu',
  },
  { name: 'University of Western States', domain: 'uws.edu' },
  { name: 'University of Wisconsin-Madison', domain: 'wisc.edu' },
  { name: 'University of Wisconsin-Milwaukee', domain: 'uwm.edu' },
  { name: 'University of Wisconsin-Oshkosh', domain: 'uwosh.edu' },
  { name: 'University of Wisconsin-Parkside', domain: 'uwp.edu' },
  { name: 'University of Wisconsin-Platteville', domain: 'uwplatt.edu' },
  { name: 'University of Wisconsin-River Falls', domain: 'uwrf.edu' },
  { name: 'University of Wisconsin-Stevens Point', domain: 'uwsp.edu' },
  { name: 'University of Wisconsin-Stout', domain: 'uwstout.edu' },
  { name: 'University of Wisconsin-Superior', domain: 'uwsuper.edu' },
  { name: 'University of Wisconsin-Whitewater', domain: 'uww.edu' },
  { name: 'University of Wyoming', domain: 'uwyo.edu' },
  { name: 'Urbana University', domain: 'urbana.edu' },
  { name: 'Ursinus College', domain: 'ursinus.edu' },
  { name: 'Ursuline College', domain: 'ursuline.edu' },
  { name: 'U. S. International University', domain: 'usiu.edu' },
  { name: 'Utah State University', domain: 'usu.edu' },
  { name: 'Utah Valley State College', domain: 'uvsc.edu' },
  { name: 'Utica College', domain: 'utica.edu' },
  { name: 'Valdosta State University', domain: 'valdosta.edu' },
  { name: 'Valley City State University', domain: 'vcsu.nodak.edu' },
  { name: 'Valparaiso University', domain: 'valpo.edu' },
  { name: 'Vanderbilt University', domain: 'vanderbilt.edu' },
  {
    name: 'Vanguard University of Southern California',
    domain: 'vanguard.edu',
  },
  { name: 'Vassar College', domain: 'vassar.edu' },
  { name: 'Vermont College', domain: 'vtc.vsc.edu' },
  { name: 'Vermont Law School', domain: 'vermontlaw.edu' },
  { name: 'Vermont Technical College', domain: 'vtc.vsc.edu' },
  { name: 'Villanova University', domain: 'villanova.edu' },
  { name: 'Virginia Commonwealth University', domain: 'vcu.edu' },
  { name: 'Virginia Intermont College', domain: 'vic.edu' },
  { name: 'Virginia Military Institute', domain: 'vmi.edu' },
  {
    name: 'Virginia Polytechnic Institute and State University',
    domain: 'vt.edu',
  },
  { name: 'Virginia State University', domain: 'vsu.edu' },
  { name: 'Virginia Union University', domain: 'vuu.edu' },
  { name: 'Virginia Wesleyan College', domain: 'vwc.edu' },
  { name: 'Viterbo College', domain: 'viterbo.edu' },
  { name: 'Voorhees College', domain: 'voorhees.edu' },
  { name: 'Wabash College', domain: 'wabash.edu' },
  { name: 'Wagner College', domain: 'wagner.edu' },
  { name: 'Wake Forest University', domain: 'wfu.edu' },
  { name: 'Walden University', domain: 'waldenu.edu' },
  { name: 'Walla Walla College', domain: 'wwc.edu' },
  { name: 'Walsh University', domain: 'walsh.edu' },
  { name: 'Warner Pacific College', domain: 'warnerpacific.edu' },
  { name: 'Warner Southern College', domain: 'warner-southern.edu' },
  { name: 'Warren Wilson College', domain: 'warren-wilson.edu' },
  { name: 'Wartburg College', domain: 'wartburg.edu' },
  { name: 'Washington and Lee University', domain: 'wlu.edu' },
  { name: 'Washington College', domain: 'washcoll.edu' },
  { name: 'Washington State University', domain: 'wsu.edu' },
  {
    name: 'Washington State University-Vancouver',
    domain: 'vancouver.wsu.edu',
  },
  { name: 'Washington University', domain: 'wustl.edu' },
  { name: 'Wayland Baptist University', domain: 'wbu.edu' },
  { name: 'Wayne State College', domain: 'wsc.edu' },
  { name: 'Wayne State University', domain: 'wayne.edu' },
  { name: 'Waynesburg College', domain: 'waynesburg.edu' },
  { name: 'Webb Institute', domain: 'webb-institute.edu' },
  { name: 'Webber College', domain: 'webber.edu' },
  { name: 'Webster University', domain: 'webster.edu' },
  { name: 'Wellesley College', domain: 'wellesley.edu' },
  { name: 'Wells College', domain: 'wells.edu' },
  { name: 'Wentworth Institute of Technology', domain: 'wit.edu' },
  { name: 'Wesley College', domain: 'wesley.edu' },
  { name: 'Wesleyan College', domain: 'wesleyancollege.edu' },
  { name: 'Wesleyan University', domain: 'wesleyan.edu' },
  { name: 'West Chester University of Pennsylvania', domain: 'wcupa.edu' },
  { name: 'West Liberty State College', domain: 'wlsc.wvnet.edu' },
  { name: 'West Texas A&M University', domain: 'wtamu.edu' },
  { name: 'West Virginia Institute of Technology', domain: 'wvit.wvnet.edu' },
  { name: 'West Virginia State College', domain: 'wvsc.edu' },
  { name: 'West Virginia University', domain: 'wvu.edu' },
  {
    name: 'West Virginia University Institute of Technology',
    domain: 'wvit.wvnet.edu',
  },
  { name: 'West Virginia Wesleyan College', domain: 'wvwc.edu' },
  { name: 'Western Carolina University', domain: 'wcu.edu' },
  { name: 'Western Connecticut State University', domain: 'wcsu.edu' },
  { name: 'Western Governors University', domain: 'wgu.edu' },
  { name: 'Western Illinois University', domain: 'wiu.edu' },
  { name: 'Western Kentucky University', domain: 'wku.edu' },
  { name: 'Western Maryland College', domain: 'wmdc.edu' },
  { name: 'Western Michigan University', domain: 'wmich.edu' },
  { name: 'Western New England College', domain: 'wnec.edu' },
  { name: 'Western New Mexico University', domain: 'wnmu.edu' },
  { name: 'Western Oregon University', domain: 'wou.edu' },
  { name: 'Western State College', domain: 'wsc.edu' },
  { name: 'Western State University College of Law', domain: 'wsulaw.edu' },
  { name: 'Western Washington University', domain: 'wwu.edu' },
  { name: 'Westfield State College', domain: 'wsc.ma.edu' },
  { name: 'Westminster College', domain: 'westminster.edu' },
  { name: 'Westminster College Fulton', domain: 'westminster-mo.edu' },
  {
    name: 'Westminster College of Salt Lake City',
    domain: 'westminstercollege.edu',
  },
  { name: 'Westminster Theological Seminary', domain: 'wts.edu' },
  { name: 'Westmont College', domain: 'westmont.edu' },
  { name: 'Wheaton College', domain: 'wheaton.edu' },
  { name: 'Wheeling Jesuit College', domain: 'wheeling.edu' },
  { name: 'Wheelock College', domain: 'wheelock.edu' },
  { name: 'Whitman College', domain: 'whitman.edu' },
  { name: 'Whittier College', domain: 'whittier.edu' },
  { name: 'Whitworth College', domain: 'whitworth.edu' },
  { name: 'Wichita State University', domain: 'twsu.edu' },
  { name: 'Widener University', domain: 'widener.edu' },
  { name: 'Wilberforce University', domain: 'wilberforce.edu' },
  { name: 'Wilkes University', domain: 'wilkes.edu' },
  { name: 'Willamette University', domain: 'willamette.edu' },
  { name: 'William Carey College', domain: 'wmcarey.edu' },
  { name: 'William Jewell College', domain: 'william.jewell.edu' },
  { name: 'William Mitchell College of Law', domain: 'wmitchell.edu' },
  { name: 'William Penn College', domain: 'wmpenn.edu' },
  { name: 'William Tyndale College', domain: 'tyndale.edu' },
  { name: 'William Woods University', domain: 'williamwoods.edu' },
  { name: 'Williams Baptist College', domain: 'williamsbaptistcollege.com' },
  { name: 'Williams College', domain: 'williams.edu' },
  { name: 'Wilmington College', domain: 'wilmington.edu' },
  { name: 'Wilson College', domain: 'wilson.edu' },
  { name: 'Wingate University', domain: 'wingate.edu' },
  { name: 'Winona State University', domain: 'winona.edu' },
  { name: 'Winston-Salem State University', domain: 'wssu.edu' },
  { name: 'Winthrop University', domain: 'winthrop.edu' },
  { name: 'Wisconsin Lutheran College', domain: 'wlc.edu' },
  { name: 'Wittenberg University', domain: 'wittenberg.edu' },
  { name: 'Wofford College', domain: 'wofford.edu' },
  { name: 'Woodbury University', domain: 'woodbury.edu' },
  { name: 'Worcester Polytechnic Institute', domain: 'wpi.edu' },
  { name: 'Worcester State College', domain: 'worcester.edu' },
  { name: 'Wright State University', domain: 'wright.edu' },
  { name: 'Xavier University', domain: 'xavier.edu' },
  { name: 'Xavier University of Louisiana', domain: 'xula.edu' },
  { name: 'Yale University', domain: 'yale.edu' },
  { name: 'Yeshiva University', domain: 'yu.edu' },
  { name: 'York College Nebraska', domain: 'york.edu' },
  { name: 'York College of Pennsylvania', domain: 'ycp.edu' },
  { name: 'Youngstown State University', domain: 'ysu.edu' },
];
